// art/<name>-frames.json -> src/art/frames.js
const fs = require('fs');

// Hold time per frame in ms, per species. The passing poses read quick and the
// contact poses hold; tune these numbers alone, the player reads them straight
// out of the data.
//
// Every species totals the same 900ms even though Kong has four frames and the
// others three. The landing page runs all three side by side and recolours them
// together on each cycle boundary — with unequal cycles there is no shared
// boundary to switch on, and they would drift apart within seconds.
const TIMING = {
  monkey: [200, 500, 200],
  ape: [200, 500, 200],
  kong: [115, 335, 115, 335],
};

const NAMES = { monkey: 'CHIMP_WALK', ape: 'APE_WALK', kong: 'KONG_WALK' };

const out = [
  '// Generated by tools/mkframes.cjs from images/*/frame*.png - do not hand-edit.',
  '//',
  "// Walk cycles. Every frame shares its species' palette, slots, anchors and base",
  "// colours, so a token's rolled colours light all frames with no extra work: only",
  '// `rows` differs between them.',
  '//',
  '// Registration: frames are aligned on the ground (the feet stay put while the',
  '// body rises and falls) and horizontally on a head marker — Kong on its brown',
  "// head patch, the ape on its face skin, the chimp on its pale mask.",
  '',
  "import { monkey, ape, kong } from './sprites.js';",
  '',
];

const SPRITE_VAR = { monkey: 'monkey', ape: 'ape', kong: 'kong' };

for (const [name, varName] of Object.entries(NAMES)) {
  const A = JSON.parse(fs.readFileSync(`art/${name}-frames.json`, 'utf8'));
  const sp = SPRITE_VAR[name];
  const slots = A.extraSlots.length
    ? `[...${sp}.slots, ${A.extraSlots.map(([role, tone, hex]) => `['${role}', ${tone}] /* ${hex} */`).join(', ')}]`
    : `${sp}.slots`;

  out.push(`export const ${varName} = {`);
  out.push(`  name: '${name}',`);
  out.push(`  w: ${A.w}, h: ${A.h},`);
  out.push(`  base: ${sp}.base,`);
  out.push(`  anchors: ${sp}.anchors,`);
  if (A.extraSlots.length) {
    out.push('  // These frames need a tone the static pose never shows (see `extra` in');
    out.push('  // extract-frames.cjs); the static sprite never references the extra index.');
  }
  out.push(`  slots: ${slots},`);
  out.push(`  timing: [${TIMING[name].join(', ')}],`);
  out.push('  frames: [');
  A.frames.forEach((f, i) => {
    out.push(`    [ // frame ${i + 1}`);
    for (const row of f) out.push(`      '${row.map((v) => v.toString(16)).join('')}',`);
    out.push('    ],');
  });
  out.push('  ],', '};', '');
}

out.push(
  'export const WALKS = { monkey: CHIMP_WALK, ape: APE_WALK, kong: KONG_WALK };',
  '',
  '/// A frame as a plain sprite, so every renderer works on it unchanged.',
  'export function frameSprite(walk, i) {',
  '  return { ...walk, rows: walk.frames[i], frames: undefined };',
  '}',
  '',
  '/// Total cycle length in ms.',
  'export const cycleMs = (walk) => walk.timing.reduce((a, b) => a + b, 0);',
  '',
);

fs.writeFileSync('src/art/frames.js', out.join('\n'));
for (const [name, varName] of Object.entries(NAMES)) {
  const A = JSON.parse(fs.readFileSync(`art/${name}-frames.json`, 'utf8'));
  console.log(`${varName.padEnd(11)} ${A.frames.length} frames  ${A.w}x${A.h}  cycle ${TIMING[name].reduce((a, b) => a + b, 0)}ms`);
}
console.log('wrote src/art/frames.js');
