const fs = require('fs');
const { execFileSync } = require('child_process');

// Only the semantic role of each extracted palette index is declared by hand.
// The lightness relationship between a slot and its role's base colour is
// measured off the source art, so the numbers cannot drift from the pixels.
const ROLES = {
  ape: [
    'bg',    // #000000
    'fur',   // #4a413a
    'skin',  // #f2c08e
    'skin',  // #dba977  face shading
    'eye',   // #fffefb
    'fur',   // #34302d  body shading
    'skin',  // #e8c29c  single-cell resample artefact
  ],
  kong: [
    'bg',    // #000000
    'fur',   // #747884  silverback saddle
    'crown', // #77716b  lit top edge of the head patch
    'crown', // #6b5c4f
    'crown', // #493b29  brown head patch
    'fur',   // #60616a
    'fur',   // #57595d
    'fur',   // #383a40  body shading
    'fur',   // #6c6d76  rim where the shoulder meets the face
    'face',  // #6d6561
    'face',  // #554e47  muzzle plate
    'eye',   // #fffdf9
  ],
  monkey: [
    'bg',    // #000000
    'fur',   // #a25b15
    'bg',    // #1b0000  near-black edge artefact
    'fur',   // #975d23
    'limb',  // #524d4a  tail and limbs
    'fur',   // #6e3e0e  deep shading
    'face',  // #dedfdc  pale mask
    'face',  // #fffffd  glint
    'fur',   // #794715  body shading
  ],
};

// The colour each role is keyed on: the source tone that role shades from.
const BASE = {
  ape:    { fur: '#4a413a', skin: '#f2c08e', eye: '#fffefb', bg: '#000000' },
  kong:   { fur: '#57595d', crown: '#493b29', face: '#554e47', eye: '#fffdf9', bg: '#000000' },
  monkey: { fur: '#a25b15', limb: '#524d4a', face: '#dedfdc', bg: '#000000' },
};

// toneBetween lives in an ESM module; call it out of process rather than
// duplicating the colour maths here.
function tones(pairs) {
  const src = `import{toneBetween}from'../src/art/shade.js';` +
    `console.log(JSON.stringify(${JSON.stringify(pairs)}.map(([a,b])=>toneBetween(a,b))));`;
  fs.writeFileSync('tools/.tone.mjs', src);
  const out = execFileSync(process.execPath, ['tools/.tone.mjs'], { encoding: 'utf8' });
  fs.unlinkSync('tools/.tone.mjs');
  return JSON.parse(out);
}

const out = [
  '// Generated by tools/mkspr.cjs from images/*.png - do not hand-edit.',
  '//',
  '// Each sprite is a grid of palette indices, one hex digit per cell, one string',
  '// per row. `slots` maps an index to [role, tone]: the renderer looks up the',
  "// role's base colour and shades it by that tone (see shade.js), so a whole",
  '// sprite recolours from one colour per role and keeps the original shading.',
  '',
];

for (const name of ['monkey', 'ape', 'kong']) {
  const art = JSON.parse(fs.readFileSync(`art/${name}.json`, 'utf8'));
  const roles = ROLES[name];
  if (roles.length !== art.palette.length)
    throw new Error(`${name}: ${art.palette.length} colours but ${roles.length} roles`);
  const t = tones(art.palette.map((hex, i) => [BASE[name][roles[i]], hex]));
  // artefact slots are folded onto their role's base rather than kept as a tone
  const ARTEFACT = { monkey: [2], ape: [6], kong: [] };
  ARTEFACT[name].forEach((i) => { t[i] = 1; });

  out.push(`export const ${name} = {`);
  out.push(`  name: '${name}',`);
  out.push(`  w: ${art.w}, h: ${art.h},`);
  out.push(`  base: ${JSON.stringify(BASE[name])},`);
  // Accent roles are positioned relative to fur, exactly as the source art has
  // them: the gorilla's face plate is only 8% darker than its body, so pinning
  // accents to absolute colours makes the face read as a hole on bright fur.
  // 'eye' is deliberately not anchored: it reads as a specular highlight rather
  // than a lit surface, and relighting it to the anchor would wash a coloured
  // pair back to near-white.
  const accents = Object.keys(BASE[name]).filter((r) => !['fur', 'bg', 'eye'].includes(r));
  const anch = tones(accents.map((r) => [BASE[name].fur, BASE[name][r]]));
  out.push(`  anchors: {${accents.map((r, i) => `${r}:${anch[i]}`).join(', ')}},`);
  out.push(`  slots: [${roles.map((r, i) => `['${r}',${t[i]}]`).join(', ')}],`);
  out.push(`  source: ${JSON.stringify(art.palette)},`);
  out.push('  rows: [');
  for (const row of art.rows) out.push(`    '${row.map((v) => v.toString(16)).join('')}',`);
  out.push('  ],');
  out.push('};', '');
}
out.push('export const SPRITES = { monkey, ape, kong };', '');
fs.writeFileSync('src/art/sprites.js', out.join('\n'));
console.log('wrote src/art/sprites.js');
